### PR TITLE
Fixed issue where mouse leaving the table left the hover class activated

### PR DESCRIPTION
**Pull request by natehitze**
When the mouse leaves the table, the hover class will be removed.

### CODE REVIEW

**Comment by freqdec** [comment]
5 months to reply. Must be a record - many, many apologies, it's really bad behaviour on my part. 

This issue was actually fixed on one of the earlier updates. Again, many apologies for being so slack.

**Comment by natehitze** [comment]
Does the demo run the latest version of the code? The hover issue is still present in the demo page.

**Comment by freqdec** [comment]
No, I still have to update the demo page.

**Comment by freqdec** [comment]
I've just updated the demo page to use the latest minified version.

**Comment by natehitze** [comment]
Thanks! I don't know how I missed that update.

**Pull request closed without merging**
