### PR TITLE
Make leading zeroes optional in date parsing

### PR DESCRIPTION
**Pull request by gdavison**
Make leading zeroes optional in date parsing even if output format
specifies them.

We were running into the following problem:
Our application uses American date style with leading zeroes, i.e. mm/dd/YYYY, and the picker is restricted to today and later.
The user wanted to back-date an item, so typed in the previous day without the leading zero. When the date field lost focus, the month and day values reversed themselves. So 9 June 2012 (6/9/2012) would become 6 September 2012 (09/06/2012).

Also added Jasmine tests.

### CODE REVIEW

**Comment by freqdec** [comment]
Hi, the problem isn't the leading zeros (which are not required), it's that the script does it's best to parse a valid date from the user input. In this case, it parsed a European date (6 september). 

This is a well known gotcha in date parsers and the only solution would be to update the code to accept a "strict parse" flag that would never attempt to parse a European date format if an American date format is required (or vice versa). This, of course, would mean a much stricter parser and may affect the ease of use in  the eyes of the user.

Shall have a look at the jasmine tests...

**Comment by gdavison** [comment]
Hi, finally getting back to you...

In our case, it was a problem with the leading zeroes, and a few other things. It's a little complex:
We want dates to _display_ with a leading zero, and for some reason in the American style, so the date format is the "American-style with leading zeroes" format. Our users were manually entering dates, and backdating them for "business" reasons, even though the picker (but not our back-end) was set to only allow today and later.

Because  there were no leading zeroes (and the date entered was in the past?), the parsing didn't match the set "American-style with leading zeroes" format. This made the date parsing switch to the fallback of trying all formats until something matched. Because the fallback list puts the logical date order before the American date order and the date happened to be in the first 12 days of the month, the parser recognized 6/9/2012 as 6 September 2012, rather than 9 June 2012 as the user expected.

After parsing using the logical date format, it displayed it in the American with leading zeroes date format: 6/9/2012 switched to 09/06/2012.

My fix tweaked the parser to ignore the leading zeroes setting on the date formats.

Possibly there should be a way to separate the date display format from the date input parsing, since there are potentially issues beyond leading zeroes, such as abbreviations. Some way of handling manual input of dates outside the valid range should be included, too.

**Comment by freqdec** [comment]
Hi - well, after spending way too much time thinking about this (and date parsing in general), I've updated the script to use the Date.parse method when attempting to parse full dates from user input. This may seem like a cowards way out by some and heroic by others - I think it may be somewhere in-between.

Here's what happens:
- The date format assigned to the input is parsed against the user input

If that didn't produce a valid date then:
- If a language file has been downloaded, all month names in that language are replaced by their English counterparts e.g. the French "mars" would be replaced by the English "March"
- Any English ordinal suffix is removed from the string i.e. st, nd, rd, th
- Any dashes are replaced by "/" (as some browsers just don't like dashes)
- We pass the resulting String to the Date.parse method and let the browser do the heavy lifting

The Date.parse method should, theoretically, parse a string representing an RFC2822 or ISO 8601 date - which would have, in this instance, parsed the missing zeros. 

It won't work every time of course but it would undoubtedly beat anything I would hazard to write.

Date parsing sucks. Date parsing in Javascript sucks even more.

I'm interested to hear more about how you would handle the out of range stuff (callbacks? extra paramater added to callback object?). It's nice to get feedback from real world situations like this.

**Comment by gdavison** [comment]
Yeah, date parsing is miserable, especially with all of the ambiguous formats. And then we let _users_ enter them... :)

Your solution sounds good; I'll have to give it a try in production.

For the out of range case, I think it would depend on the actual reason for why a site restricts to a date range. In our case, it has to do with the activation date of content. There's no real reason for us to restrict the date, other than our usual case is to activate on creation or later. The simplest solution would probably be to throw up an error of some kind if a user manually enters an out-of-range date.

Thanks for looking into this.

**Pull request closed without merging**
